#!/usr/bin/with-contenv sh

apk add mariadb mariadb-client

/usr/bin/mysql_install_db --user=mysql --rpm

#/usr/bin/mysqladmin -u root password "${MYSQL_PASSWORD}"
#/usr/bin/mysqladmin -u root -h "$(hostname)" password "${MYSQL_PASSWORD}"
